/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ErrType.h"
#include "Stm32F103xx.h"

#include "RCC_Interface.h"
#include "GPIO_interface.h"

int main(void)
{
	uint8_t Local_u8SwIsPRESSED = INIT_VALUE_BY_ONE;

	/* Configuration struct for PORTA pin0 */
	PinConfig_t PinB0 =
	{
			.Port = PORTB,
			.PinNum = PIN11,
			.Mode = INPUT,
			.CNF_InputMode = INPUT_PU_OR_PD,
	};



	/* Configuration struct for PORTA pin0 */
	PinConfig_t PinC13 =
	{
			.Port = PORTC,
			.PinNum = PIN13,
			.Mode = OUTPUT_MAXSPEED_10MHZ,
			.CNF_InputMode = Reserved_CFR,
			.CNF_OutputMode = PUSH_PULL,
	};

	/* I work on GPIOC ===> PIN13 and it connects with APB2  */

			RCC_voidAPB_2_EnableClk(IOPB_EN);
			GPIO_u8PinInit(&PinB0);



	/* Loop forever */
	for(;;)
	{
		GPIO_u8ReadPinValue(PORTB, PIN11, &Local_u8SwIsPRESSED);
		/* POLLING  */
		while(Local_u8SwIsPRESSED == ONE_VALUE)
		{
			/* READ IF switch pressed or not  */
			GPIO_u8ReadPinValue(PORTB, PIN11, &Local_u8SwIsPRESSED);
		}

		/* CHECK AGIAN as sw is pressed */
		if(Local_u8SwIsPRESSED == ZERO_VALUE)
		{

			/* I work on GPIOC ===> PIN13 and it connects with APB2  */

			RCC_voidAPB_2_EnableClk(IOPC_EN);
			GPIO_u8PinInit(&PinC13);
			/* this pin which reading on f446 and tack a decision on it */
			GPIO_u8SetPinValue(PORTC, PIN13, PIN_HIGH);
		}else
		{

		}
	}
}
