/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ErrType.h"
#include "Stm32F446xx.h"

#include "RCC_Interface.h"
#include "GPIO_interface.h"

int main(void)
{
	uint8_t Local_u8Signal = INIT_VALUE_BY_ZERO;
	PinConfig_t	PinA0 =
	{
			.Port= PORTA ,
			.PinNum =PIN0,
			.Mode = INPUT,
			//.PullType = PULLDOWN,
	};


	PinConfig_t	UserLed2_t =
	{
			.Port= PORTA ,
			.PinNum =PIN5,
			.Mode = OUTPUT,
			.OutputType = PUSH_PULL,
	};

	RCC_voidAHB_1_EnableClk(GPIOA_EN);

	GPIO_u8PinInit(&PinA0);


	GPIO_u8ReadPinValue(PORTA, PIN0, &Local_u8Signal);
	/* POLLING  */
	while(Local_u8Signal == ZERO_VALUE)
	{
		/* READ IF switch pressed or not  */
		GPIO_u8ReadPinValue(PORTA, PIN0, &Local_u8Signal);
	}

	/* CHECK AGIAN as sw is pressed */
	if(Local_u8Signal == ONE_VALUE)
	{

		/* I work on GPIOA ===> PIN5*/
		GPIO_u8PinInit(&UserLed2_t);
		/* USER LED IS ON */
		GPIO_u8SetPinValue(PORTA, PIN5, PIN_HIGH );
	}else
	{

	}

	/* Loop forever */
	for(;;);
}
